### PR TITLE
dummy_urls: changed all urls to actual image urls from gatech.edu.

### PR DESCRIPTION
**Pull request by jcarroll2007**
Changed dummy urls in tests to actual image urls from gatech.edu

### CODE REVIEW

**Comment by sathomas** [comment]
Unit tests need updating as well

**Comment by jcarroll2007** [comment]
Should I just remove the `oae` url part?

**Comment by jcarroll2007** [comment]
Is this alright to merge in?

**Comment by jcarroll2007** [comment]
Is this alright to merge in?

**Comment by sathomas** [comment]
I don't think you have the right permissions to merge into the repo, but, in any case, I'll handle it after I verify the PR locally. Not high on the priority list, but I'll try to get to it soonish.

**Comment by jcarroll2007** [comment]
I didn't think so. It was more of a reminder. :)

**Pull request closed without merging**
